"""
pages/7_About.py — About

Displays:
  - Project architecture
  - Methodology
"""

import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="About — Byrnihat",
    page_icon="ℹ️",
    layout="wide",
)

CSS = Path(__file__).parents[1] / "assets" / "style.css"
if CSS.exists():
    st.markdown(f"<style>{CSS.read_text(encoding='utf-8')}</style>",
                unsafe_allow_html=True)

st.markdown("## ℹ️ About the Byrnihat Air Pollution System")

st.markdown("""
This system is a research-grade, machine-learning-driven platform for predicting air quality and simulating pollution dispersion in the Byrnihat industrial corridor along the Assam-Meghalaya border.

### Methodology

The pipeline involves two main machine learning stages and a physical simulation:

1. **ML-1 (Environment & Pollution Prediction)**: 
   Uses NASA POWER meteorological data and AQICN observed air quality data to train `ExtraTreesRegressor` models. This stage predicts 11 targets, including PM2.5, PM10, various gases (SO2, CO, NO2, O3, NH3, NO, NOx), and wind vectors (U and V components).

2. **Simulation (PM10 Diffusion)**: 
   Uses a 2D Laplacian diffusion model, seeded with data from known industrial emission sources (weighted by their potential PM10 output). The diffusion occurs over a grid overlaying the Byrnihat region terrain, simulating how pollution disperses geographically over 150 time steps.

3. **ML-2 (Plume Direction Prediction)**: 
   Trains on the spatial relationships between industrial sources and the peak pollution concentrations generated by the diffusion simulation. It predicts the expected angle and strength of the pollution plume from any given source under varying environmental conditions.

### Architecture

This Streamlit application acts purely as a **presentation layer**. 
- It **does not** retrain models or run heavy simulations in real-time. 
- It reads pre-computed outputs (CSV, JSON) generated by the underlying Python backend pipeline (`ml/10_run_final_prediction_pipeline.py`).
- Interactive maps are built natively in Python using `Plotly` and `PyDeck`, replacing the older static HTML/Folium dashboard.
""")

st.info("The original backend Python scripts (in `ml/`, `simulation/`, `analysis/`, and `mapping/`) remain completely unmodified. The Streamlit backend cleanly wraps these original files to extract data for visualization.")
